package ui;

import com.sun.org.apache.bcel.internal.generic.DDIV;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.VerticalAlignment;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mohan
 */
public class CashCusomers extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public CashCusomers() {
        initComponents();

        refresh();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfCustomerName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCustomerAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfCustomerPhoneNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCustomerID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfProductCode = new javax.swing.JTextField();
        tfProductPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        tfSearch1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMProducts = new javax.swing.JMenu();
        jMCashCustomers = new javax.swing.JMenu();
        jMInstCustomers = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Add Product");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Add Customer");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("عملاء الكاش");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "الناريخ", "الوقت"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(3);
            table.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        jPanel2.setBackground(new java.awt.Color(39, 34, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("اسم العميل");

        tfCustomerName.setColumns(10);
        tfCustomerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfCustomerName.setToolTipText("ادخل اسم المنتج");
        tfCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCustomerNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("العنوان");

        tfCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCustomerAddressActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("رقم الهاتف");

        tfCustomerPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCustomerPhoneNumberActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("رقم البطاقه");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("كود المنتج");

        tfProductCode.setColumns(10);
        tfProductCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfProductCode.setToolTipText("ادخل اسم المنتج");
        tfProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductCodeActionPerformed(evt);
            }
        });

        tfProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductPriceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("المبلغ");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_buy_product.png"))); // NOI18N
        jButton1.setText("شراء منتج");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_excel.png"))); // NOI18N
        jButton3.setText("تصدير كملف اكسيل");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_delete_customer.png"))); // NOI18N
        jButton2.setText("حذف عميل");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(255, 255, 255));
        btExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_back.png"))); // NOI18N
        btExit.setText("الغاء");
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExitMouseExited(evt);
            }
        });
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        tfSearch1.setBackground(new java.awt.Color(39, 34, 90));
        tfSearch1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSearch1.setForeground(new java.awt.Color(255, 255, 255));
        tfSearch1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSearch1.setBorder(null);
        tfSearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearch1ActionPerformed(evt);
            }
        });
        tfSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSearch1KeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_search.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("عملاء الكاش");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSearch1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfCustomerAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfCustomerName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfCustomerPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfProductCode)
                                        .addComponent(tfProductPrice)
                                        .addComponent(tfCustomerID))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tfSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btExit)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenuBar3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar3.setForeground(new java.awt.Color(39, 34, 90));

        jMenu8.setText("الصفحة الرئيسية");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu8);

        jMProducts.setText("المنتجات");
        jMProducts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMProductsMouseClicked(evt);
            }
        });
        jMenuBar3.add(jMProducts);

        jMCashCustomers.setText("عملاء الكاش");
        jMCashCustomers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMCashCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMCashCustomersMouseClicked(evt);
            }
        });
        jMenuBar3.add(jMCashCustomers);

        jMInstCustomers.setText("عملاء القسط");
        jMInstCustomers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMInstCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMInstCustomersMouseClicked(evt);
            }
        });
        jMenuBar3.add(jMInstCustomers);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductCodeActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            String query = "select * from product where name like ?";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, tfProductCode.getText());
            DefaultTableModel model = new DefaultTableModel();
            table.setModel(model);
            Object[] col = {"ID", "اسمم المنتج", "الرقم التسلسلي", "السعر", "الكميه", "التاريخ", "الوقت"};
            model.setColumnIdentifiers(col);
            ResultSet res = st.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt("idProduct"),
                    res.getString("name"),
                    res.getString("code"),
                    res.getString("price"),
                    res.getString("count"),
                    res.getString("date"),
                    res.getString("time")

                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tfProductCodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // JOptionPane.showMessageDialog(null, "done ");

        if (tfCustomerName.getText().length() == 0
                || tfCustomerAddress.getText().length() == 0
                || tfCustomerPhoneNumber.getText().length() == 0
                || tfCustomerID.getText().length() == 0
                || tfProductCode.getText().length() == 0
                || tfProductPrice.getText().length() == 0) {

            JOptionPane.showMessageDialog(null,
                    "من فضلك يجب ادخل جميع البيانات",
                    "معلومات",
                    JOptionPane.INFORMATION_MESSAGE);

            return;
        }

        try {
            Double.parseDouble(tfProductPrice.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "هذه البيانات غير منطقية",
                    "معلومات",
                    JOptionPane.INFORMATION_MESSAGE);

            return;
        }

        String productName = "";
        String productTotalPrice = "";
        String count = "";

        // select product info from the product id 
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            PreparedStatement st = con.prepareStatement("select name, price, count from product where code =?");
            st.setString(1, tfProductCode.getText());

            ResultSet res = st.executeQuery();
            while (res.next()) {
                productName = res.getString("name");
                productTotalPrice = res.getString("price");
                count = res.getString("count");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {

            if (productName.equals("") || productTotalPrice.equals("") || count.equals("")) {
                JOptionPane.showMessageDialog(null,
                        "هذا المنتج غير موجود, تاكد من كود المنتج",
                        "معلومات",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (Double.parseDouble(tfProductPrice.getText()) > Double.parseDouble(productTotalPrice)) {
                JOptionPane.showMessageDialog(null,
                        "هذا المبغ اكبر من ثمن المنتج",
                        "معلومات",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (Double.parseDouble(tfProductPrice.getText()) < Double.parseDouble(productTotalPrice)) {
                JOptionPane.showMessageDialog(null,
                        "هذا المبغ اقل من ثمن المنتج",
                        "معلومات",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (Double.parseDouble(count) == 0) {
                JOptionPane.showMessageDialog(null,
                        "عفوا هذا المنتج منتهي",
                        "معلومات",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
            System.out.println("Connected Done !");
            PreparedStatement st = con.prepareStatement("insert into cashCustomer (name, address, phoneNumber, idNumber, productCode, price, totalPrice, productName, date, time) values(?,?,?,?,?,?,?,?,?,?);");

            st.setString(1, tfCustomerName.getText());
            st.setString(2, tfCustomerAddress.getText());
            st.setString(3, tfCustomerPhoneNumber.getText());
            st.setString(4, tfCustomerID.getText());
            st.setString(5, tfProductCode.getText());
            st.setString(6, productTotalPrice);
            st.setString(7, tfProductPrice.getText());
            st.setString(8, productName);

            String formatedDate = formatDate(new Date());
            st.setString(9, formatedDate);

            String formatedTime = formatTime(new Date());
            st.setString(10, formatedTime);

            st.execute();
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
            System.out.println("Connected Done !");
            PreparedStatement st = con.prepareStatement("update product set count =? where code=?;");

            int c = 0;
            if (Integer.parseInt(count) > 0) {
                c = Integer.parseInt(count) - 1;
            } else {
                System.out.println("count is 0");
            }

            st.setString(1, String.valueOf(c));
            st.setString(2, tfProductCode.getText());

            st.execute();
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        tfCustomerName.setText("");
        tfCustomerAddress.setText("");
        tfCustomerPhoneNumber.setText("");
        tfCustomerID.setText("");
        tfProductCode.setText("");
        tfProductPrice.setText("");

        refresh();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        TableModel model1 = table.getModel();
        String id = null;
        try {
            id = model1.getValueAt(index, 0).toString();
        } catch (ArrayIndexOutOfBoundsException ex) {
            System.out.println("array bound exception");
        }

        if (id != null) {

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
                PreparedStatement st = con.prepareStatement("delete from cashCustomer where id =?");
                st.setString(1, id);
                st.execute();
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            return;
        }

        tfCustomerName.setText("");
        tfCustomerAddress.setText("");
        tfCustomerPhoneNumber.setText("");
        tfCustomerID.setText("");
        tfProductCode.setText("");
        tfProductPrice.setText("");

        refresh();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductPriceActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:

        tfSearch1.setText("");
        tfCustomerName.setText("");
        tfCustomerAddress.setText("");
        tfCustomerPhoneNumber.setText("");
        tfCustomerID.setText("");
        tfProductCode.setText("");
        tfProductPrice.setText("");

        refresh();
    }//GEN-LAST:event_btExitActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        try {
            int index = table.getSelectedRow();
            TableModel model1 = table.getModel();
            String name = model1.getValueAt(index, 1).toString();
            String address = model1.getValueAt(index, 2).toString();
            String phoneNumber = model1.getValueAt(index, 3).toString();
            String idNumber = model1.getValueAt(index, 4).toString();
            String productCode = model1.getValueAt(index, 5).toString();
            String price = model1.getValueAt(index, 7).toString();

            tfCustomerName.setText(name);
            tfCustomerAddress.setText(address);
            tfCustomerPhoneNumber.setText(phoneNumber);
            tfCustomerID.setText(idNumber);
            tfProductCode.setText(productCode);
            tfProductPrice.setText(price);
        } catch (NullPointerException e) {
            System.out.println("null poniter exception");
        }


    }//GEN-LAST:event_tableMouseClicked

    private void tfCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCustomerNameActionPerformed

    private void tfCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCustomerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCustomerAddressActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Welcome frame = new Welcome();
        frame.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Products frame = new Products();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        CashCusomers frame = new CashCusomers();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet sheet = workbook.createSheet("List Cutmoers");

            Row rowHeading = sheet.createRow(0);
            rowHeading.createCell(0).setCellValue("ID");
            rowHeading.createCell(1).setCellValue("اسم العميل");
            rowHeading.createCell(2).setCellValue("العنوان");
            rowHeading.createCell(3).setCellValue("رقم الهاتف");
            rowHeading.createCell(4).setCellValue("رقم البطاقه");
            rowHeading.createCell(5).setCellValue("كود المنتج");
            rowHeading.createCell(6).setCellValue("سعر المنتج");
            rowHeading.createCell(7).setCellValue("المبلغ المدفوع");
            rowHeading.createCell(8).setCellValue("اسم المنتج");

            for (int i = 0; i < 8; i++) {
                CellStyle styleWorkHeading = workbook.createCellStyle();
                HSSFFont font = workbook.createFont();
                font.setBold(true);
                font.setFontName(HSSFFont.FONT_ARIAL);
                font.setFontHeightInPoints((short) 11);
                styleWorkHeading.setFont(font);
                styleWorkHeading.setVerticalAlignment(VerticalAlignment.CENTER);
                rowHeading.getCell(i).setCellStyle(styleWorkHeading);

            }

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
                PreparedStatement st = con.prepareStatement("select * from cashCustomer ;");

                ResultSet res = st.executeQuery();
                int row = 1;
                while (res.next()) {
                    Row r = sheet.createRow(row++);
                    Cell cellID = r.createCell(0);
                    cellID.setCellValue(res.getInt("id"));

                    Cell cellName = r.createCell(1);
                    cellName.setCellValue(res.getString("name"));

                    Cell cellAddress = r.createCell(2);
                    cellAddress.setCellValue(res.getString("address"));

                    Cell cellPhoneNumber = r.createCell(3);
                    cellPhoneNumber.setCellValue(res.getString("phoneNumber"));

                    Cell cellIdNumber = r.createCell(4);
                    cellIdNumber.setCellValue(res.getString("idNumber"));

                    Cell cellProductCode = r.createCell(5);
                    cellProductCode.setCellValue(res.getString("productCode"));

                    Cell cellPrice = r.createCell(6);
                    cellPrice.setCellValue(Float.parseFloat(res.getString("price")));

                    Cell cellTotalPrice = r.createCell(7);
                    cellTotalPrice.setCellValue(Float.parseFloat(res.getString("totalPrice")));

                    Cell cellProductName = r.createCell(8);
                    cellProductName.setCellValue(res.getString("productName"));
                };

                for (int i = 0; i < 8; i++) {
                    sheet.autoSizeColumn(i);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }

            // save to path
            save = new JButton("save to file");
            JFileChooser fileChooser = new JFileChooser();
            FileOutputStream fos = null;

            int retval = fileChooser.showDialog(save, null);
            if (retval == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                if (file == null) {
                    return;
                }

                if (!file.getName().toLowerCase().endsWith(".xls")) {
                    String currentDate = formatDate(new Date());
                    file = new File(file.getParentFile(), file.getName() + "_" + currentDate + ".xls");
                }
                try {
                    fos = new FileOutputStream(file);
                    workbook.write(fos);
                    Desktop.getDesktop().open(file);
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    fos.close();
                    workbook.close();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearch1ActionPerformed

    private void tfSearch1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearch1KeyTyped
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            String query = "select * from cashCustomer where name like ?";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, tfSearch1.getText() + "%");
            DefaultTableModel model = new DefaultTableModel();
            table.setModel(model);
            JTableHeader header = table.getTableHeader();
            header.setFont(new Font("Arial", Font.BOLD, 14));
            header.setForeground(new Color(39, 34, 90));
            Object[] col = {"ID", "اسم العميل", "العنوان", "رقم الهاتف", "رقم البطاقه", "كود المنتج", "سعر المنتج", "المبغ المدفوع", "اسم المنتج"};
            model.setColumnIdentifiers(col);
            ResultSet res = st.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt("id"),
                    res.getString("name"),
                    res.getString("address"),
                    res.getString("phoneNumber"),
                    res.getString("idNumber"),
                    res.getString("productCode"),
                    res.getString("price"),
                    res.getString("totalPrice"),
                    res.getString("productName"),});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tfSearch1KeyTyped

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Welcome frame = new Welcome();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMProductsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Products frame = new Products();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMProductsMouseClicked

    private void jMCashCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCashCustomersMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        CashCusomers frame = new CashCusomers();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMCashCustomersMouseClicked

    private void jMInstCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMInstCustomersMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();

        InstallmentCusomers frame = new InstallmentCusomers();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMInstCustomersMouseClicked

    private void tfCustomerPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCustomerPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCustomerPhoneNumberActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(39, 34, 90));
        jButton1.setForeground(Color.white);

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.black);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setBackground(new Color(39, 34, 90));
        jButton3.setForeground(Color.white);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setBackground(Color.white);
        jButton3.setForeground(Color.black);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(new Color(39, 34, 90));
        jButton2.setForeground(Color.white);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(Color.white);
        jButton2.setForeground(Color.black);
    }//GEN-LAST:event_jButton2MouseExited

    private void btExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseEntered
        // TODO add your handling code here:
        btExit.setBackground(new Color(39, 34, 90));
        btExit.setForeground(Color.white);
    }//GEN-LAST:event_btExitMouseEntered

    private void btExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseExited
        // TODO add your handling code here:
        btExit.setBackground(Color.white);
        btExit.setForeground(Color.black);
    }//GEN-LAST:event_btExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashCusomers().setVisible(true);
            }
        });
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
    }

    /**
     * Return the formatted date string (i.e. "Mar 3, 1984") from a Date object.
     */
    private String formatDate(Date dateObject) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("LLL dd, yyyy");
        return dateFormat.format(dateObject);
    }

    /**
     * Return the formatted date string (i.e. "4:30 PM") from a Date object.
     */
    private String formatTime(Date dateObject) {
        SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
        return timeFormat.format(dateObject);
    }

    private void refresh() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            PreparedStatement st = con.prepareStatement("select * from cashCustomer ;");
            DefaultTableModel model = new DefaultTableModel();
            table.setModel(model);
            JTableHeader header = table.getTableHeader();
            header.setFont(new Font("Arial", Font.BOLD, 14));
            header.setForeground(new Color(39, 34, 90));
            Object[] col = {"ID", "اسم العميل", "العنوان", "رقم الهاتف", "رقم البطاقه", "كود المنتج", "سعر المنتج", "المبغ المدفوع", "اسم المنتج", "التاريخ", "الوقت"};
            model.setColumnIdentifiers(col);
            ResultSet res = st.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt("id"),
                    res.getString("name"),
                    res.getString("address"),
                    res.getString("phoneNumber"),
                    res.getString("idNumber"),
                    res.getString("productCode"),
                    res.getString("price"),
                    res.getString("totalPrice"),
                    res.getString("productName"),
                    res.getString("date"),
                    res.getString("time"),});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private JButton save;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMCashCustomers;
    private javax.swing.JMenu jMInstCustomers;
    private javax.swing.JMenu jMProducts;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfCustomerAddress;
    private javax.swing.JTextField tfCustomerID;
    private javax.swing.JTextField tfCustomerName;
    private javax.swing.JTextField tfCustomerPhoneNumber;
    private javax.swing.JTextField tfProductCode;
    private javax.swing.JTextField tfProductPrice;
    private javax.swing.JTextField tfSearch1;
    // End of variables declaration//GEN-END:variables
}
