package ui;

import com.sun.org.apache.bcel.internal.generic.DDIV;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.VerticalAlignment;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mohan
 */
public class InstallmentCusomers extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public InstallmentCusomers() {
        initComponents();

        refresh();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfCustomerName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCustomerAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfCustomerPhoneNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCustomerID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfProductCode = new javax.swing.JTextField();
        tfProductFront = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        tfSearch1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfProductRate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Insttabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfInstCustomerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfInstProductCode = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfInstProductPrice = new javax.swing.JTextField();
        jbBuy = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Add Product");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Add Customer");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("عملاء القسط");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(4).setHeaderValue("Title 5");
            table.getColumnModel().getColumn(5).setHeaderValue("Title 6");
            table.getColumnModel().getColumn(6).setHeaderValue("Title 7");
            table.getColumnModel().getColumn(7).setHeaderValue("Title 8");
            table.getColumnModel().getColumn(8).setHeaderValue("Title 9");
        }

        jPanel2.setBackground(new java.awt.Color(39, 34, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("اسم العميل");

        tfCustomerName.setColumns(10);
        tfCustomerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfCustomerName.setToolTipText("ادخل اسم المنتج");
        tfCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCustomerNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("العنوان");

        tfCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCustomerAddressActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("رقم الهاتف");

        tfCustomerPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("رقم البطاقه");

        tfCustomerID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("كود المنتج");

        tfProductCode.setColumns(10);
        tfProductCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfProductCode.setToolTipText("ادخل اسم المنتج");
        tfProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductCodeActionPerformed(evt);
            }
        });

        tfProductFront.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfProductFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductFrontActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("المقدم");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_buy_product.png"))); // NOI18N
        jButton1.setText("شراء منتج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_excel.png"))); // NOI18N
        jButton3.setText("تصدير كملف اكسيل");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_delete_customer.png"))); // NOI18N
        jButton2.setText("حذف عميل");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(255, 255, 255));
        btExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sm_back.png"))); // NOI18N
        btExit.setText("الغاء");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        tfSearch1.setBackground(new java.awt.Color(39, 34, 90));
        tfSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfSearch1.setForeground(new java.awt.Color(255, 255, 255));
        tfSearch1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSearch1.setBorder(null);
        tfSearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearch1ActionPerformed(evt);
            }
        });
        tfSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSearch1KeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_search.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("النسبه المؤية");

        tfProductRate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfProductRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductRateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("عملاء القسط");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSearch1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(tfCustomerAddress)
                                    .addComponent(tfCustomerID)
                                    .addComponent(tfCustomerPhoneNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfProductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfProductCode, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                            .addComponent(tfProductFront))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tfSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProductFront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btExit)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Insttabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Insttabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Insttabel.setGridColor(new java.awt.Color(255, 255, 255));
        Insttabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsttabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Insttabel);

        jPanel3.setBackground(new java.awt.Color(39, 34, 90));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ساداد قسط", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("اسم العميل");

        tfInstCustomerName.setColumns(10);
        tfInstCustomerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfInstCustomerName.setToolTipText("ادخل اسم المنتج");
        tfInstCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInstCustomerNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("كود المنتج");

        tfInstProductCode.setColumns(10);
        tfInstProductCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfInstProductCode.setToolTipText("ادخل اسم المنتج");
        tfInstProductCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInstProductCodeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("المبغ");

        tfInstProductPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfInstProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInstProductPriceActionPerformed(evt);
            }
        });

        jbBuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbBuy.setText("سداد");
        jbBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbBuy)
                        .addGap(49, 49, 49)
                        .addComponent(tfInstProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfInstProductCode, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfInstCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfInstCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfInstProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfInstProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuy)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jMenu4.setText("الصفحة الرئيسية");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu5.setText("المنتجات");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu5);

        jMenu6.setText("عملاء الكاش");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        jMenu7.setText("عملاء القسط");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductCodeActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            String query = "select * from product where name like ?";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, tfProductCode.getText());
            DefaultTableModel model = new DefaultTableModel();
            table.setModel(model);
            Object[] col = {"ID", "اسمم المنتج", "الرقم التسلسلي", "السعر", "الكميه", "التاريخ", "الوقت"};
            model.setColumnIdentifiers(col);
            ResultSet res = st.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt("idProduct"),
                    res.getString("name"),
                    res.getString("code"),
                    res.getString("price"),
                    res.getString("count"),
                    res.getString("date"),
                    res.getString("time")

                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tfProductCodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // JOptionPane.showMessageDialog(null, "done ");

        // check if data entry is empty or not
        if (tfCustomerName.getText().length() == 0
                || tfCustomerAddress.getText().length() == 0
                || tfCustomerPhoneNumber.getText().length() == 0
                || tfCustomerID.getText().length() == 0
                || tfProductCode.getText().length() == 0
                || tfProductFront.getText().length() == 0
                || tfProductRate.getText().length() == 0) {

            JOptionPane.showMessageDialog(null,
                    "من فضلك يجب ادخل جميع البيانات",
                    "معلومات",
                    JOptionPane.INFORMATION_MESSAGE);

            return;
        }

        String productName = "";
        String productTotalPrice = "";
        String count = "";
        double totalPrice = 0;
        double front = 0;
        double remainingPrice = 0;
        double rate = 0;
        double price = 0;

        // select product info from the product id 
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            PreparedStatement st = con.prepareStatement("select name, price, count from product where code =?");
            st.setString(1, tfProductCode.getText());

            ResultSet res = st.executeQuery();
            while (res.next()) {
                productName = res.getString("name");
                productTotalPrice = res.getString("price");
                count = res.getString("count");
            }

            try {

                rate = Double.parseDouble(tfProductRate.getText());
                price = Double.parseDouble(productTotalPrice);
                front = Double.parseDouble(tfProductFront.getText());

                double x = price - front;
                totalPrice = (x) + ((rate / 100) * x);
                remainingPrice = totalPrice - front;

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "هذه البيانات غير متطابقه",
                        "معلومات",
                        JOptionPane.INFORMATION_MESSAGE);

                return;
            }

        } catch (Exception ex) {
            System.out.println(ex.toString());
        } finally {
            if (productName.equals("") || productTotalPrice.equals("") || count.equals("")) {
                JOptionPane.showMessageDialog(null,
                        "هذا المنتج غير موجود, تاكد من كود المنتج",
                        "معلومات",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

        if (Integer.parseInt(count) == 0) {
            System.out.println("count equal 0");
            return;
        }

        if (front > totalPrice) {
                JOptionPane.showMessageDialog(null,
                        "المقدم اكبر من سعر المنتج",
                        "معلومات",
                        JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // insert data into installments customers
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
            System.out.println("Connected Done !");
            PreparedStatement st = con.prepareStatement("insert into installmentcustomers (name, address, phoneNumber, idNumber, productCode, productName, totalPrice, currentPrice, remainingPrice) values(?,?,?,?,?,?,?,?,?);");

            st.setString(1, tfCustomerName.getText());
            st.setString(2, tfCustomerAddress.getText());
            st.setString(3, tfCustomerPhoneNumber.getText());
            st.setString(4, tfCustomerID.getText());
            st.setString(5, tfProductCode.getText());
            st.setString(6, productName);

            st.setString(7, String.valueOf(totalPrice));
            st.setString(8, String.valueOf(front));
            st.setString(9, String.valueOf(remainingPrice));

            /*
             String formatedDate = formatDate(new Date());
             st.setString(5, formatedDate);

             String formatedTime = formatTime(new Date());
             st.setString(6, formatedTime);
             */
            st.execute();
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // update product count number
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
            System.out.println("Connected Done !");
            PreparedStatement st = con.prepareStatement("update product set count =? where code=?;");

            int c = Integer.parseInt(count) - 1;

            st.setString(1, String.valueOf(c));
            st.setString(2, tfProductCode.getText());

            st.execute();
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        refresh();

        // insert and refresh installments
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
            System.out.println("Connected Done !");
            PreparedStatement st = con.prepareStatement("insert into installments (name, productName, productCode, installment )  values(?,?,?,?);");

            st.setString(1, tfCustomerName.getText());
            st.setString(2, productName);
            st.setString(3, tfProductCode.getText());
            st.setString(4, tfProductFront.getText());

            /*
             String formatedDate = formatDate(new Date());
             st.setString(5, formatedDate);

             String formatedTime = formatTime(new Date());
             st.setString(6, formatedTime);
             */
            st.execute();
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        refreshInstallments(tfCustomerName.getText(), tfProductCode.getText());

        tfCustomerName.setText("");
        tfCustomerAddress.setText("");
        tfCustomerPhoneNumber.setText("");
        tfCustomerID.setText("");
        tfProductCode.setText("");
        tfProductFront.setText("");
        tfProductRate.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        TableModel model1 = table.getModel();
        String id = null;
        try {
            id = model1.getValueAt(index, 0).toString();
        } catch (ArrayIndexOutOfBoundsException ex) {
            System.out.println("array bound exception");
        }

        if (id != null) {

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
                PreparedStatement st = con.prepareStatement("delete from installmentcustomers where id =?");
                st.setString(1, id);
                st.execute();
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            return;
        }

        if (tfInstCustomerName.getText().length() == 0 || tfInstProductCode.getText().length() == 0) {
            return;
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            PreparedStatement st = con.prepareStatement("delete from installments where name =? and productCode =?;");
            st.setString(1, tfInstCustomerName.getText());
            st.setString(2, tfInstProductCode.getText());

            st.execute();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        tfCustomerName.setText("");
        tfCustomerAddress.setText("");
        tfCustomerPhoneNumber.setText("");
        tfCustomerID.setText("");
        tfProductCode.setText("");
        tfProductFront.setText("");
        tfProductRate.setText("");
        
        tfInstCustomerName.setText("");
        tfInstProductCode.setText("");
        tfInstProductPrice.setText("");
        
        refresh();
        refreshInstallments("", "");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfProductFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductFrontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductFrontActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:

        tfSearch1.setText("");
        tfCustomerName.setText("");
        tfCustomerAddress.setText("");
        tfCustomerPhoneNumber.setText("");
        tfCustomerID.setText("");
        tfProductCode.setText("");
        tfProductFront.setText("");
        tfProductRate.setText("");
        
        
        tfInstCustomerName.setText("");
        tfInstProductCode.setText("");
        tfInstProductPrice.setText("");
       
        refreshInstallments("", "");
        refresh();
    }//GEN-LAST:event_btExitActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        try {
            int index = table.getSelectedRow();
            TableModel model1 = table.getModel();
            String name = model1.getValueAt(index, 1).toString();
            String address = model1.getValueAt(index, 2).toString();
            String phoneNumber = model1.getValueAt(index, 3).toString();
            String idNumber = model1.getValueAt(index, 4).toString();
            String productCode = model1.getValueAt(index, 5).toString();
            String currentPrice = model1.getValueAt(index, 8).toString();

            /*
            tfCustomerName.setText(name);
            tfCustomerAddress.setText(address);
            tfCustomerPhoneNumber.setText(phoneNumber);
            tfCustomerID.setText(idNumber);
            tfProductCode.setText(productCode);
            tfProductFront.setText(currentPrice);
            */

            tfInstCustomerName.setText(name);
            tfInstProductCode.setText(productCode);

            refreshInstallments(name, productCode);

        } catch (NullPointerException e) {
            System.out.println("null poniter exception");
        }


    }//GEN-LAST:event_tableMouseClicked

    private void tfCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCustomerNameActionPerformed

    private void tfCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCustomerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCustomerAddressActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Welcome frame = new Welcome();
        frame.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Products frame = new Products();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        InstallmentCusomers frame = new InstallmentCusomers();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Welcome frame = new Welcome();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        Products frame = new Products();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        CashCusomers frame = new CashCusomers();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet sheet = workbook.createSheet("List Cutmoers");

            Row rowHeading = sheet.createRow(0);
            rowHeading.createCell(0).setCellValue("ID");
            rowHeading.createCell(1).setCellValue("اسم العميل");
            rowHeading.createCell(2).setCellValue("العنوان");
            rowHeading.createCell(3).setCellValue("رقم الهاتف");
            rowHeading.createCell(4).setCellValue("رقم البطاقه");
            rowHeading.createCell(5).setCellValue("كود المنتج");
            rowHeading.createCell(6).setCellValue("سعر المنتج");
            rowHeading.createCell(7).setCellValue("المبلغ المدفوع");
            rowHeading.createCell(8).setCellValue("اسم المنتج");

            for (int i = 0; i < 8; i++) {
                CellStyle styleWorkHeading = workbook.createCellStyle();
                HSSFFont font = workbook.createFont();
                font.setBold(true);
                font.setFontName(HSSFFont.FONT_ARIAL);
                font.setFontHeightInPoints((short) 11);
                styleWorkHeading.setFont(font);
                styleWorkHeading.setVerticalAlignment(VerticalAlignment.CENTER);
                rowHeading.getCell(i).setCellStyle(styleWorkHeading);

            }

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
                PreparedStatement st = con.prepareStatement("select * from cashCustomer ;");

                ResultSet res = st.executeQuery();
                int row = 1;
                while (res.next()) {
                    Row r = sheet.createRow(row++);
                    Cell cellID = r.createCell(0);
                    cellID.setCellValue(res.getInt("id"));

                    Cell cellName = r.createCell(1);
                    cellName.setCellValue(res.getString("name"));

                    Cell cellAddress = r.createCell(2);
                    cellAddress.setCellValue(res.getString("address"));

                    Cell cellPhoneNumber = r.createCell(3);
                    cellPhoneNumber.setCellValue(res.getString("phoneNumber"));

                    Cell cellIdNumber = r.createCell(4);
                    cellIdNumber.setCellValue(res.getString("idNumber"));

                    Cell cellProductCode = r.createCell(5);
                    cellProductCode.setCellValue(res.getString("productCode"));

                    Cell cellPrice = r.createCell(6);
                    cellPrice.setCellValue(Float.parseFloat(res.getString("price")));

                    Cell cellTotalPrice = r.createCell(7);
                    cellTotalPrice.setCellValue(Float.parseFloat(res.getString("totalPrice")));

                    Cell cellProductName = r.createCell(8);
                    cellProductName.setCellValue(res.getString("productName"));
                };

                for (int i = 0; i < 8; i++) {
                    sheet.autoSizeColumn(i);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }

            // save to path
            save = new JButton("save to file");
            JFileChooser fileChooser = new JFileChooser();
            FileOutputStream fos = null;

            int retval = fileChooser.showDialog(save, null);
            if (retval == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                if (file == null) {
                    return;
                }

                if (!file.getName().toLowerCase().endsWith(".xls")) {
                    String currentDate = formatDate(new Date());
                    file = new File(file.getParentFile(), file.getName() + "_" + currentDate + ".xls");
                }
                try {
                    fos = new FileOutputStream(file);
                    workbook.write(fos);
                    Desktop.getDesktop().open(file);
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    fos.close();
                    workbook.close();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearch1ActionPerformed

    private void tfSearch1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearch1KeyTyped
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            String query = "select * from installmentcustomers where name like ?";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, tfSearch1.getText() + "%");
            DefaultTableModel model = new DefaultTableModel();
            table.setModel(model);
            Object[] col = {"ID", "اسم العميل", "العنوان", "رقم الهاتف", "رقم البطاقه", "كود المنتج", "اسم المنتج", "السعر الكلي", "المبلغ المدفوع", "المتبقي"};
            model.setColumnIdentifiers(col);
            ResultSet res = st.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt("id"),
                    res.getString("name"),
                    res.getString("address"),
                    res.getString("phoneNumber"),
                    res.getString("idNumber"),
                    res.getString("productCode"),
                    res.getString("productName"),
                    res.getString("totalPrice"),
                    res.getString("currentPrice"),
                    res.getString("remainingPrice"),});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tfSearch1KeyTyped

    private void tfProductRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductRateActionPerformed

    private void InsttabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsttabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InsttabelMouseClicked

    private void tfInstCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInstCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInstCustomerNameActionPerformed

    private void tfInstProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInstProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInstProductCodeActionPerformed

    private void tfInstProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInstProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInstProductPriceActionPerformed

    private void jbBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuyActionPerformed
        // TODO add your handling code here:
        // update buyed price
        if (tfInstCustomerName.getText().length() == 0
                || tfInstProductCode.getText().length() == 0
                || tfInstProductPrice.getText().length() == 0) {

            return;
        }
        String id = "";
        String currentPrice = "";
        String totalPrice = "";
        String productName = "";
        String reminderOldPrice = "";

        try {
            int index = table.getSelectedRow();
            TableModel model1 = table.getModel();
            id = model1.getValueAt(index, 0).toString();

            productName = model1.getValueAt(index, 6).toString();;
            totalPrice = model1.getValueAt(index, 7).toString();
            currentPrice = model1.getValueAt(index, 8).toString();
            reminderOldPrice = model1.getValueAt(index, 9).toString();

        } catch (NullPointerException e) {
            System.out.println("null poniter exception");
        }

        if (Double.parseDouble(tfInstProductPrice.getText()) > Double.parseDouble(reminderOldPrice) || Double.parseDouble(reminderOldPrice) == 0) {
            JOptionPane.showMessageDialog(null,
                    "المبلغ اكبر من المتبقي, او لايوجد متبقي",
                    "معلومات",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // update product count number
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
            System.out.println("Connected Done !");
            PreparedStatement st = con.prepareStatement("update installmentcustomers set currentPrice =?, remainingPrice=? where id=?;");

            double newPrice = Double.parseDouble(tfInstProductPrice.getText()) + Double.parseDouble(currentPrice);

            double reminderPrice = Double.parseDouble(totalPrice) - newPrice;

            st.setString(1, String.valueOf(newPrice));
            st.setString(2, String.valueOf(reminderPrice));

            st.setInt(3, Integer.parseInt(id));

            st.execute();
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        refresh();

        // insert into installments
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tailor", "root", "root");
            System.out.println("Connected Done !");
            PreparedStatement st = con.prepareStatement("insert into installments (name, productName, productCode, installment ) values(?,?,?,?);");

            st.setString(1, tfCustomerName.getText());
            st.setString(2, productName);
            st.setString(3, tfInstProductCode.getText());
            st.setString(4, tfInstProductPrice.getText());

            /*
             String formatedDate = formatDate(new Date());
             st.setString(5, formatedDate);

             String formatedTime = formatTime(new Date());
             st.setString(6, formatedTime);
             */
            st.execute();
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        refreshInstallments(tfCustomerName.getText(), tfInstProductCode.getText());

        tfInstCustomerName.setText("");
        tfInstProductCode.setText("");
        tfInstProductPrice.setText("");

    }//GEN-LAST:event_jbBuyActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        
        this.setVisible(false);
        this.dispose();
        
        InstallmentCusomers frame = new InstallmentCusomers();
        frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstallmentCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstallmentCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstallmentCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstallmentCusomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstallmentCusomers().setVisible(true);
            }
        });
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
    }

    /**
     * Return the formatted date string (i.e. "Mar 3, 1984") from a Date object.
     */
    private String formatDate(Date dateObject) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("LLL dd, yyyy");
        return dateFormat.format(dateObject);
    }

    /**
     * Return the formatted date string (i.e. "4:30 PM") from a Date object.
     */
    private String formatTime(Date dateObject) {
        SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
        return timeFormat.format(dateObject);
    }

    private void refresh() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            PreparedStatement st = con.prepareStatement("select * from installmentcustomers ;");
            DefaultTableModel model = new DefaultTableModel();
            table.setModel(model);
            Object[] col = {"ID", "اسم العميل", "العنوان", "رقم الهاتف", "رقم البطاقه", "كود المنتج", "اسم المنتج", "السعر الكلي", "المبلغ المدفوع", "المتبقي"};
            model.setColumnIdentifiers(col);
            ResultSet res = st.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt("id"),
                    res.getString("name"),
                    res.getString("address"),
                    res.getString("phoneNumber"),
                    res.getString("idNumber"),
                    res.getString("productCode"),
                    res.getString("productName"),
                    res.getString("totalPrice"),
                    res.getString("currentPrice"),
                    res.getString("remainingPrice"),});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private JButton save;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Insttabel;
    private javax.swing.JButton btExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbBuy;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfCustomerAddress;
    private javax.swing.JTextField tfCustomerID;
    private javax.swing.JTextField tfCustomerName;
    private javax.swing.JTextField tfCustomerPhoneNumber;
    private javax.swing.JTextField tfInstCustomerName;
    private javax.swing.JTextField tfInstProductCode;
    private javax.swing.JTextField tfInstProductPrice;
    private javax.swing.JTextField tfProductCode;
    private javax.swing.JTextField tfProductFront;
    private javax.swing.JTextField tfProductRate;
    private javax.swing.JTextField tfSearch1;
    // End of variables declaration//GEN-END:variables

    private void refreshInstallments(String name, String code) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tailor", "root", "root");
            PreparedStatement st = con.prepareStatement("select * from installments where name =? and productCode =?;");
            st.setString(1, name);
            st.setString(2, code);

            DefaultTableModel model = new DefaultTableModel();
            Insttabel.setModel(model);
            Object[] col = {"اسم العميل", "اسم المنتج", "كود المنتج", "الاقساط"};
            model.setColumnIdentifiers(col);
            ResultSet res = st.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("name"),
                    res.getString("productName"),
                    res.getString("productCode"),
                    res.getString("installment"),});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
